CREATE TABLE footnotes (
    id SERIAL PRIMARY KEY,
    uid INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    date_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    content TEXT NOT NULL
);
